import = ["/home/ilya/.config/alacritty/colors/mocha.toml"]

[font]
size = 12

[font.normal]
family = "Source Code Pro"
#family = "Geist Mono"
style = "Regular"

[font.bold]
family = "Source Code Pro"
#family = "Geist Mono"
style = "Bold"

[font.italic]
family = "Source Code Pro"
#family = "Geist Mono"
style = "Italic"

[font.offset]
x = 0
y = 0

[font.glyph_offset]
x = 0
y = 0

[window]
dynamic_title = false
opacity = 1.0
title = "Alacritty"

[window.dimensions]
columns = 90
lines = 30

[window.padding]
x = 10
y = 10
