#1F2229 : black
#D41919 : dark red
#5EBDAB : another light green
#FEA44C : another orange
#367bf0 : another blue
#9755b3 : dark purple
#49AEE6 : light blue
#E6E6E6 : light gray
#198388 : aquamarine
#EC0101 : red
#47D4B9 : light green
#FF8A18 : orange
#277FFF : blue
#962ac3 : purple
#05A1F7 : light blue
#FFFFFF : white

[colors.normal]
black = "#1f2229"
blue = "#367bf0"
cyan = "#277fff"
green = "#47d4b9"
magenta = "#05a1f7"
red = "#ec0101"
white = "#198388"
yellow = "#ff8a18"

[colors.primary]
background = "#1f2229"
foreground = "#e0def4"

[colors.bright]
black = "#26233a"
blue = "#9ccfd8"
cyan = "#c4a7e7"
green = "#31748f"
magenta = "#ebbcba"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.cursor]
cursor = "#524f67"
text = "#e0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.selection]
background = "#403d52"
text = "#e0def4"

[colors.vi_mode_cursor]
cursor = "#524f67"
text = "#e0def4"
