[colors.bright]
black = "#26233a"
blue = "#9ccfd8"
cyan = "#c4a7e7"
green = "#31748f"
magenta = "#ebbcba"
red = "#eb6f92"
white = "#e0def4"
yellow = "#f6c177"

[colors.cursor]
cursor = "#524f67"
text = "#e0def4"

[colors.hints.end]
background = "#1f1d2e"
foreground = "#6e6a86"

[colors.hints.start]
background = "#1f1d2e"
foreground = "#908caa"

[colors.line_indicator]
background = "None"
foreground = "None"

[colors.normal]
black = "#11121d"
blue = "#6DA1FD"
cyan = "#c4a7e7"
green = "#00d787"
magenta = "#ff5faf"
red = "#FE4E46"
white = "#e0def4"
yellow = "#ffaf00"

[colors.primary]
#background = "#0a0f12"
background = "#000000"
#foreground = "#eeeeee"

[colors.selection]
background = "#403d52"
text = "#e0def4"

[colors.vi_mode_cursor]
cursor = "#524f67"
text = "#e0def4"
